name: Build and Publish

env:
  AWS_REGION: us-east-1
  INFRA_GIT_REPO: Beatly-src/infra
  SERVICE_NAME: test-beatly-fe
  PROJECT_NAME_WITHOUT_ENV: beatly

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  determine-environment:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
    steps:
      - name: Determine environment
        id: determine-env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=stage" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    name: Build and Publish to ECR
    needs: determine-environment
    environment: ${{ needs.determine-environment.outputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.determine-environment.outputs.environment }}-${{ env.PROJECT_NAME_WITHOUT_ENV }}-services
          SERVICE_TAG: ${{ env.SERVICE_NAME }}-${{ github.sha }}
          LATEST_TAG: ${{ env.SERVICE_NAME }}-latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SERVICE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SERVICE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG
          echo "IMAGE_TAG=$SERVICE_TAG" >> $GITHUB_ENV
          echo "REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV

      - name: Trigger deployment
        env:
          ENVIRONMENT: ${{ needs.determine-environment.outputs.environment }}
          GH_TOKEN: ${{ secrets.INFRA_GIT_REPO_TOKEN }}
        run: |
          # Encode all repository secrets
          ENCODED_SECRETS=$(echo '${{ toJSON(secrets) }}' | base64 -w 0)

          # Prepare the payload for the infrastructure repository workflow
          PAYLOAD=$(cat <<EOF
          {
            "ref": "main",
            "inputs": {
              "service": "${{ env.SERVICE_NAME }}",
              "environment": "$ENVIRONMENT",
              "image_tag": "$IMAGE_TAG",
              "region": "${{ env.AWS_REGION }}",
              "project_name": "$ENVIRONMENT-${{ env.PROJECT_NAME_WITHOUT_ENV }}",
              "service_secrets": "$ENCODED_SECRETS"
            }
          }
          EOF
          )

          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ env.INFRA_GIT_REPO }}/actions/workflows/update-and-deploy.yml/dispatches \
            -d "$PAYLOAD"
